TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += mrf-vmeevg230.db
DB += mrf-vmeevg230-sequencer.db
DB += mrf-vmeevg230-event.db
DB += mrf-vmeevg230-counter.db
DB += mrf-vmeevr230.db
DB += mrf-vmeevr230-event.db
DB += mrf-vmeevr230-pulser.db
DB += mrf-vmeevr230-pdp.db
DB += mrf-vmeevr230-prescaler.db
DB += mrf-vmeevr230-ttl.db
DB += mrf-vmeevr230-univ.db
DB += mrf-vmeevr230-cml.db
DB += power_seq.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

